# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: light'blog
description: 学如逆水行舟，不进则退 ❤
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wtgunag.github.io" # the base hostname & protocol for your site
nav:
  - about
  - posts
  - categories
  - download
avatar_url: https://secure.gravatar.com/avatar/deb3a965cd52a9103cd865bbf01de5af
twitter_username:
github_username: wtguang
codepen_username:  wtguang
linkedin_username:  james-shih-15277934
instagram_username:  wtguang
500px_username:  wtguang
disqus_shortname: wtguang
google_analytics:

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: /:year/:month/:day/:title.html
highlighter: rouge
gist:
  noscript: false
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
