# Site settings
title: light'blog
description: > # this means to ignore newlines until "baseurl:"
  Magic happens.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wtguang.github.io" # the base hostname & protocol for your site
nav:
  - about
  - posts
  - categories
  - download
avatar_url: https://wtguang.github.io/media/images.jpg
twitter_username:
github_username:  wtguang
codepen_username:  wtguang
linkedin_username:  james-shih-15277934
instagram_username:  wtguang
500px_username:  wtguang
disqus_shortname: wtguang
google_analytics: 

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: /:year/:month/:day/:title.html
highlighter: rouge
gist:
  noscript: false
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
